### ISSUE TITLE
Opimization idea

### ISSUE THREAD

**Issue by TheDiamondYT1** [scar45/aokp-co-webviewer#3]
How about setting a custom user agent, for example 

```
aokp-app
```

then checking the user agent on the site like

``` javascript
if(navigator.userAgent == "aokp-app"){
//Stuff
}
```

And change parts of the site around to optimize for the app.

If you really wanted to add some cool things to INTERACT with the app, you could use a custom javascript interface and call the functions from the site

**Comment by scar45** [comment]
This is certainly a great idea, however the site hasn't been updated in a long while, since this is a hobby project. Don't get me wrong though, because if I do start to work on it again, and can come up with some neat app <--> site interactions, I certainly will. Thanks for the suggestions!
